name: lint records
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # skipping ogm v1 for efficiency
      # - name: lint v1 records
      #   run: bundle exec rake lint:v1
      - name: lint aardvark records
        run: bundle exec rake lint:aardvark
