name: lint records
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # run linters
      - name: lint v1 records
        run: bundle exec rake lint:v1
